### ISSUE TITLE
[#Epic #17][#Task 3] cancel / create label 버튼 이벤트 구현

### ISSUE THREAD

**Issue by jch422** [boostcamp-2020/IssueTracker-24#100]
📖 관련 Epic
새로운 레이블을 생성할 수 있다. #79 

🥇 완료 조건
- [ ] Cancel 버튼을 누르면 아무런 반영 없이 새로운 레이블 추가 영역이 사라지고 이전 슬라이드와 같이 레이블 목록만 보여진다.
- [ ] 레이블 이름을 입력하면 Create label 버튼이 활성화된다
- [ ] Create label 버튼을 누르면 입력한 내용대로 새로운 레이블이 생성된다
