### ISSUE TITLE
[Epic #1] 사용자는 GitHub 계정을 통해 로그인 한다.

### ISSUE THREAD

**Issue by mu1616** [boostcamp-2020/IssueTracker-24#2]
## 🥇  목표
- 초기 개발환경을 세팅하고, 유저 소셜 로그인 기능을 구현한다.
- 로그인 기능 구현에 필요한 UI를 개발한다.
## 😄  완료 조건
- [x] 유저인증 방식/기술 결정 (Oauth, Passport-local, JWT) 
- [x] 브랜치 전략 적용 및 실습 
- [x] 로그인 UI 구현 
- [x] oauth 로그인 API 구현

### 🕺  로그인 UI
![image](https://user-images.githubusercontent.com/38288479/97264679-c07cc580-1868-11eb-9d3f-6fc81fa2db00.png)

## 🌲 브랜치
- feature-login
