### ISSUE TITLE
[Epic #15][Task #2] 마일스톤 제목, 날짜, 설명을 작성하고 저장한다. 

### ISSUE THREAD

**Issue by jch422** [boostcamp-2020/IssueTracker-24#32]
📖 관련 Epic
마일스톤을 생성할 수 있다. #29

🥇 완료 조건
- [x] 마일스톤 완료 날짜를 입력할 수 있다. (옵션값)
- [x] “연도. 월. 일.” 형식으로 이루어진 유효한 날짜값인지 확인(유효하지 않을 경우 해당 값을 빨간색으로 표시한다.)
- [x] 마일스톤에 대한 설명을 작성할 수 있다. (옵션값)
