### ISSUE TITLE
[Epic #3] 특정 이슈를 상세조회할 수 있다.

### ISSUE THREAD

**Issue by mu1616** [boostcamp-2020/IssueTracker-24#36]
## 🥇  목표
- 특정 이슈를 상세조회할 수 있다.
## 😄  완료 조건
- [x] 이슈 제목, 내용 ui 구현 #44
- [x] 특정 이슈 조회 api #48
- [x] 이슈 상세정보를 서버에 요청하여 받아온 후 화면에 보여준다. #50
- [x] 이슈 목록 페이지에서 특정 이슈의 제목을 클릭하면 이슈 상세조회 페이지로 라우팅 #55

### 🕺  UI
![image](https://user-images.githubusercontent.com/26829633/97824910-914ed400-1d00-11eb-9b31-ac0dc0f49f7d.png)

## 🌲 브랜치
- feature-issue-detail

### 🔥  레퍼런스
[기획서](https://docs.google.com/presentation/d/1iA-tpumHl_TpR_yUwgYcnb_X8GbW6XvjZOTh2Ucvu0A/preview?pru=AAABdYa_uas*Fuku9RAcUdMBG7REzgBhIg&slide=id.g8582887c3d_0_12)
