### ISSUE TITLE
[Epic #4][Task #1] 이슈 생성 ui 구현

### ISSUE THREAD

**Issue by mu1616** [boostcamp-2020/IssueTracker-24#57]
## 📖 관련 Epic
이슈를 생성할 수 있다. #54

## 🥇 완료 조건
- [x] 이슈 생성 페이지 ui 구현
  - Assignee, Labels, Milstone 부분은 아직 구현하지 않는다.
- [x] 이슈 내용 작성 중, 글자를 타이핑하지 않고 2초가 지나면 
내용 영역 우측 하단에 현재 입력된 글자 수가 2초간 나타났다가 사라진다.
- [x] cancel 버튼을 누르면 이슈 목록 화면으로 이동
