### ISSUE TITLE
[Epic #5][Task #2] 이슈 생성 페이지에서 Assignee 이벤트 구현

### ISSUE THREAD

**Issue by mu1616** [boostcamp-2020/IssueTracker-24#69]
## 📖 관련 Epic
이슈 생성/조회시 담당자(Assignee) 목록을 볼 수 있다. #66

## 🥇 완료조건
- [x] Assignees 부분을 클릭하면 담당자 목록 팝업이 나타난다.
- [x] 담당자를 선택하면 텍스트가 할당된 담당자로 변경된다.
- [x] assign yourself 텍스트를 클릭하면 본인이 담당자로 할당된다.
